---
output: html_document
editor_options: 
  chunk_output_type: console
---

## Load libraries

```{r}
# load libs
library(data.table)
library(ggplot2)
library(sf)
library(rnaturalearth)
```

## Data pre-processing

```{r}
# load data
data <- fread("data/elephant_data.csv")

# drop NAs
data <- na.omit(data, cols = c("xutm", "yutm"))
```

## Loacations in each 5km

```{r}
# round data
data_count <- copy(data)
data_count[, c("xutm", "yutm") := lapply(list(xutm, yutm),
                                         round, digits = -3)]

data_count <- data_count[, .N, by = list(xutm, yutm)]

# save
fwrite(data_count, file = "data/data_ele_count.csv")
```


```{r}
# make sf and lines
data <- split(data, by = "id")

# get histogram of speeds
data <- rbindlist(data)

# split data again
data <- split(data, by = c("id"))

# make multilinestring
geometry <- st_sfc(
  lapply(data, function(x) {
    st_linestring(
      as.matrix(x[, c("long", "lat")])
    )
  }),
  crs = 4326
)

# retransform
geometry <- st_transform(geometry, 32736)
```

## Make `sf`

```{r}
# get data
data_sf <- mapply(
  function(df) {
    df[1, c("id")]
  },
  data, SIMPLIFY = FALSE
)

# add geometry
data_sf <- rbindlist(data_sf)
data_sf[, geometry := geometry]

# make sf
data_sf <- st_sf(data_sf, crs = 32736)

# save
st_write(data_sf, 
         dsn = "data/data_lines_elephants.gpkg", 
         append = FALSE)
```

## Get ZA

```{r}
# get natural earth data
land <- rnaturalearth::ne_download(type = "land", 
                                   category = "physical",
                                   scale = "small",
                                   returnclass = "sf")
```

```{r crop_data}
# za box
za_box <- st_bbox(
  st_multipoint(
    matrix(c(-20, -39,
             40, -10), 
           nrow = 2,
           byrow = T)))
za_box <- st_as_sfc(za_box, crs = 4326)

# crop
za <- st_crop(land,
              za_box)

# save
st_write(za, "data/za_boundary.gpkg")
```