---
output: html_document
editor_options: 
  chunk_output_type: console
---

## Load libraries

```{r}
# load libraries
library(sf)
library(ggplot2)
library(ggspatial)
library(pals)
library(rnaturalearth)
library(data.table)
library(scico)
```

## Load data

```{r}
# prepare bounding box
bbox <- c(xmin = 337000,
          xmax = 391000,
          ymin = 7265000, 
          ymax = 7303050)
bbox_sf <- st_bbox(bbox)
bbox_sf <- st_as_sfc(bbox_sf)
st_crs(bbox_sf) <- 32736
```

```{r}
# get data
data <- st_read("data/data_lines_elephants.gpkg")

# get count data
data_count <- fread("data/data_ele_count.csv")

# get data 253
data_253 <- data[data$id == "AM253", ]

# get other data
data_rest <- data[data$id %in% c("AM255", "AM99", "AM239"), ]

# get kruger data
kruger <- st_read("data/kruger_clip/kruger_clip.shp")
kruger <- st_transform(kruger, 32736)

# get kruger point
kruger_point <- st_point(c(31.5, -24))
kruger_point = st_sfc(kruger_point, crs = 4326)
kruger_point = st_transform(kruger_point, 32736)
```

```{r}
# get za
za <- st_read("data/za_boundary.gpkg")
za <- st_transform(za, 32736)
```

```{r}
# get rivers
rivers <- st_read("data/river_crop/")

# river buffer
rivers <- st_transform(rivers[is.na(rivers$seasonal), ], 32736)
# river_buffer <- st_crop(river_buffer, bbox)
# river_buffer <- st_buffer(river_buffer, 200)
# river_buffer <- st_union(river_buffer)

# waterholes
waterholes <- st_read("data/waterholes/")
```

```{r}
# get slope
library(raster)
# elev <- raster::raster("data/kruger_elevation_UTM.tif")
# res_init <- res(elev)
# 
# # res to transform to 1000m
# res_final <- res_init * 200 / res_init
# 
# # use gdalutils gdalwarp for resampling transform
# # to 1km from 10m
# gdalUtils::gdalwarp(
#   srcfile = "data/kruger_elevation_UTM.tif",
#   dstfile = "data/kruger_elevation_200m.tif",
#   tr = c(res_final), r = "average", 
#   te = c(bbox(elev))
# )

res_init <- res(raster("data/kruger_temperature_UTM.tif"))
res_final <- res_init * 200 / res_init
gdalUtils::gdalwarp(
  srcfile = "data/kruger_temperature_UTM.tif",
  dstfile = "data/kruger_temp_200m.tif",
  tr = c(res_final), r = "average", 
  te = c(bbox(raster("data/kruger_temperature_UTM.tif")))
)

# read in cropped raster
# elev <- raster("data/kruger_elevation_200m.tif")
temp <- raster("data/kruger_temp_200m.tif")

temp <- raster::crop(temp, as(bbox_sf, "Spatial"))
temp <- cbind(coordinates(temp), values(temp))
temp <- data.table(temp)
temp <- temp[V3 > 22, ]
```

## Make main plot

```{r}
bbox <- c(xmin = 337000,
          xmax = 391000,
          ymin = 7265000, 
          ymax = 7303050)
```


```{r}
# make plot
fig_main <-
  ggplot()+
  geom_tile(
    data = temp,
    aes(x, y, fill = V3),
    show.legend = F,
    # col = "grey",
    alpha = 0.4
  )+
  geom_sf(
    data = rivers[is.na(rivers$seasonal), ],
    lwd = 1,
    col = scico::scico(3,
                       palette = "nuuk")[1],
    alpha = 0.35
  )+
  geom_sf(data = data_rest,
          lwd = c(0.1, 0.1, 0.1),
          lty = 1,
          alpha = c(0.4, 0.8, 0.1),
          col = scico::scico(7,
                        palette = "turku")[c(3, 4, 3)])+
  geom_sf(data = data_253,
          lwd = 0.15,
          alpha = 1,
          col = scico::scico(7,
                        palette = "bilbao")[6])+
  geom_sf(
    data = waterholes,
    col = scico::scico(5,
                       palette = "nuuk")[1],
    alpha = 0.35
    # col = "grey"
  )+
  geom_sf(
    data = kruger,
    col = "grey50",
    lwd = 0.2,
    fill = NA,
    lty = 2
  )+
  annotate(
    geom = "text",
    x = bbox["xmin"] + 1000,
    y = bbox["ymax"] - 1000,
    label = c("some description here"),
    hjust = "inward"
  )+
  scale_fill_gradientn(
    # colours = scico(10, palette = "lapaz",
    #                 direction = 1,
    #                 begin = 0., end = 1)
    colours = rev(RColorBrewer::brewer.pal(9, "RdYlBu"))#,
    # guide = guide_colorbar(frame.colour = "grey40",
    #                        ticks.colour = "grey40")
  )+
  annotation_north_arrow(
    style = north_arrow_minimal(text_family = "IBM Plex Sans", 
                                text_size = 10, 
                                text_col = "grey50", 
                                line_col = "grey50", 
                                fill = "grey50"),
    location = "br"
  )+
  annotation_scale(
    bar_cols = c("grey50", "grey90"),
    height = unit(1, units = "mm"), 
    text_family = "IBM Plex Sans"
  )+
  theme_void()+
  theme(
    # legend.position = c(0.8, 0.85),
    # legend.key.width = unit(1, units = "mm"),
    # legend.key.height = unit(3, units = "mm"),
    # legend.title = element_text(
    #   family = "IBM Plex Sans",
    #   colour = "grey30",
    #   size = 8
    # ),
    # legend.text = element_text(
    #   family = "IBM Plex Sans",
    #   colour = "grey30",
    #   size = 6
    # ),
    panel.background = element_rect(
      colour = "grey",
      fill = "grey99"
    ),
    plot.margin = unit(rep(5, 4), "mm")
  )+
  coord_sf(
    xlim = bbox[c("xmin", "xmax")],
    ylim = bbox[c("ymin", "ymax")],
    expand = FALSE
  )+#+
  # labs(
  #   fill = "Temp. (°C)"
  # )+
  annotation_custom(
    grob = ggplotGrob(
      fig_inset_b
    ),
    xmin = bbox[c("xmin")] + 1000,
    xmax = bbox[c("xmin")] + 7500,
    ymax = bbox["ymin"] + 13500,
    ymin = bbox["ymin"] + 1000
  )+
  annotation_custom(
    grob = ggplotGrob(
      fig_inset_a
    ),
    xmin = bbox[c("xmin")] + 1000,
    xmax = bbox[c("xmin")] + 7500,
    ymax = bbox["ymin"] + 21000,
    ymin = bbox["ymin"] + 13600
  )
```

```{r}
ggsave(fig_main, filename = "figures/fig_map2.png",
  height=9, width=13)
```

## Make where plot

```{r}
fig_inset_a <-
  ggplot()+
  geom_sf(
    data = za,
    fill = "tan",
    # alpha = 0.5,
    show.legend = F,
    col = NA
  )+
  geom_sf(
    data = kruger_point,
    size = 5
  )+
  scale_y_continuous(
    breaks = seq(-22, -34, -6)
  )+
  theme_void(base_size = 8)+
  theme(
    panel.background = element_rect(
      fill = "aliceblue",
      colour = "grey20"
    ),
    # axis.ticks = element_line(),
    # axis.ticks.length = unit(2, units = "mm"),
    # axis.text.y = element_text(margin = margin(r = -25)),
    # axis.text.x = element_text(margin = margin(t = -20)),
    # panel.grid = element_line(colour = "grey40", 
    #                           size = 0.1),
    # text = element_text(
    #   family = "IBM Plex Sans"
    # ), 
    plot.margin = unit(rep(2, 4), "mm")
  )+
  coord_sf(
    # xlim = c((bbox["xmin"] - 2e6), (bbox["xmax"] + 4e5)),
    # ylim = c(bbox["ymin"] - 1.25e6, bbox["ymax"] + 8e5),
    # crs = 32736,
    expand = FALSE
  )
```


## Make count plot

```{r}
fig_inset_b <-
  ggplot()+
  geom_sf(
    data = kruger,
    fill = "grey99",
    alpha = 1,
    col = NA,
    lwd = 0.2
  )+
  geom_sf(
    data = data,
    lwd = c(0.1),
    lty = 1,
    alpha = c(0.4),
    col = scico::scico(7,
                       palette = "bilbao")[c(6)]
  )+
  annotate(
    geom = "rect",
    fill = NA,
    col = "grey20",
    lwd = 0.3,
    xmin = bbox["xmin"], 
    xmax = bbox["xmax"],
    ymin = bbox["ymin"], 
    ymax = bbox["ymax"]
  )+
  annotation_north_arrow(
    style = north_arrow_minimal(
      text_family = "IBM Plex Sans", 
      text_size = 10, 
      text_col = "grey50", 
      line_col = "grey50", 
      fill = "grey50"),
    location = "br"
  )+
  annotation_scale(
    bar_cols = c("grey50", "grey70"), 
    height = unit(1, units = "mm"), 
    text_family = "IBM Plex Sans"
  )+
  theme_void()+
  coord_sf(crs = 32736,
           expand = FALSE,
           xlim = c(325000, NA)#,
           # ylim = c(7213050, 7335050)
           )+
  theme(
    panel.background = element_rect(
      colour = "grey20",
      # size = 0.2,
      fill = "tan"
    ),
    plot.margin = unit(rep(1, 4), "mm")
  )
```

## Marge plots

```{r}



```


```{r}
fig <-
  wrap_plots(fig_inset_b, fig_main, 
           design = "AB") +
  plot_annotation(tag_levels = "a",
                  tag_prefix = "(",
                  tag_suffix = ")") &
  theme(
    plot.margin = unit(rep(0.1, 4), units = "mm"),
    plot.tag.position = c(0.9, 0.95),
    plot.tag = element_text(
      size = 10,
      colour = "grey40",
      face = "bold",
      family = "IBM Plex Sans"
    )
  )

ggsave(fig,
       filename = "figures/fig_map.png",
       # dpi = 300,
       height = 100, 
       width = 148,
       units = "mm")
```


